global:
  scrape_interval: 15s
scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["prometheus:9090"]
  - job_name: "cadvisor"
    static_configs:
      - targets: ["cadvisor:8080"]

# alerting:
#   alertmanagers:
#   - static_configs:
#     - targets: ['alertmanager:9093']
# rule_files:
#   - "alert_rules.yml"